### ISSUE TITLE
Why is the difference in speed much smaller in fastapi example?

### ISSUE THREAD

**Issue by gitgithan** [koaning/onnx-demo#1]
When running benchmark.py, the video shows SKLEARN 3.384s and ONNX 0.101s, 30x difference.
Why in locust tests, `/predict` is Avg ~9 vs `/sk_predict` Avg ~12, not 30x difference?

**Comment by koaning** [comment]
Could be loads of reasons, these feel like the main ones:

1. the course is a few years old now
2. the video does not add overhead of fastapi. it is likely that this extra overhead is what you are measuring. 

If I had to guess, it is probably number 2 here.
